eTimeTrack/Models/Office.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Newtonsoft.Json;

namespace eTimeTrack.Models
{
    public class Office : ITrackableModel, IMergeable
    {
        [Key]
        public int Office_Id { get; set; }
        [StringLength(50, ErrorMessage = "Maximum length is 50")]
        [Display(Name = "Office Code")]
        public string Office_Code { get; set; }
        [StringLength(50, ErrorMessage = "Maximum length is 50")]
        [Display(Name = "Office Name")]
        public string Office_Name { get; set; }
        [Display(Name = "Company")]
        public int Company_Id { get; set; }

        [JsonIgnore]
        public virtual Company Company { get; set; }
        [JsonIgnore]
        public virtual ICollection<Employee> Employees { get; set; }
        [JsonIgnore]
        public virtual ICollection<Project> Projects { get; set; }

        [JsonIgnore]
        [NotMapped]
        [EditorBrowsable(EditorBrowsableState.Never)]
        [Browsable(false)]
        public Dictionary<string, bool> MergedFields { get; set; }

        public string GetId()
        {
            return Office_Id.ToString();
        }

        public string ToJson()
        {
            return JsonConvert.SerializeObject(this);
        }
    }
}

eTimeTrack/Controllers/OfficesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using eTimeTrack.Helpers;
using eTimeTrack.Models;

namespace eTimeTrack.Controllers
{
    [Authorize(Roles = UserHelpers.AuthTextAdminOrAbove)]
    public class OfficesController : BaseController
    {
        public ActionResult Index()
        {
            var offices = Db.Offices.Include(o => o.Company);
            return View(offices.ToList());
        }

        public ActionResult Create()
        {
            ViewBag.Company_Id = new SelectList(Db.Companies, "Company_Id", "Company_Code");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Office_Id,Office_Code,Office_Name,Company_Id")] Office office)
        {
            if (ModelState.IsValid)
            {
                Db.Offices.Add(office);
                Db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Company_Id = new SelectList(Db.Companies, "Company_Id", "Company_Code", office.Company_Id);
            return View(office);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return InvokeHttp400(HttpContext);
            }
            Office office = Db.Offices.Find(id);
            if (office == null)
            {
                return InvokeHttp404(HttpContext);
            }
            ViewBag.Company_Id = new SelectList(Db.Companies, "Company_Id", "Company_Code", office.Company_Id);
            return View(office);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Office_Id,Office_Code,Office_Name,Company_Id")] Office office)
        {
            if (ModelState.IsValid)
            {
                Db.Entry(office).State = EntityState.Modified;
                Db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Company_Id = new SelectList(Db.Companies, "Company_Id", "Company_Code", office.Company_Id);
            return View(office);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Office office = Db.Offices.Find(id);
            Db.Offices.Remove(office);
            Db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                Db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

eTimeTrack/Views/Offices/Create.cshtml
@model eTimeTrack.Models.Office

@{
    ViewBag.Title = "Create";
}

<h2>Add Office</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Office_Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Office_Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Company_Id", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
            </div>
        </div>


            <div class="pull-right">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        <a href="@Url.Action("Index")" class="btn btn-primary">Back</a>
    </div>
}

eTimeTrack/Views/Offices/Edit.cshtml
@model eTimeTrack.Models.Office

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Office</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Office_Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Office_Code, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office_Code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office_Code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Office_Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Office_Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Office_Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Company_Id, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Company_Id", null, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Company_Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="pull-right">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
        <a href="@Url.Action("Index")" class="btn btn-primary">Back</a>
    </div>

}

eTimeTrack/Views/Offices/Index.cshtml
@model IEnumerable<eTimeTrack.Models.Office>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    <a href="@Url.Action("Create", "Offices")" class="btn btn-primary">Add Office</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Company.Company_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Office_Code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Office_Name)
        </th>
        <th>Edit</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Company.Company_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Office_Code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Office_Name)
        </td>
        <td>
           @* @Html.ActionLink("Edit", "Edit", new { id=item.Office_Id })*@
            @*@Html.ActionLink("Details", "Details", new { id=item.Office_Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Office_Id })*@
            <a href='@Url.Action("Edit", new {id=item.Office_Id})' class="btn btn-primary" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
        </td>
    </tr>
}

</table>

<a href="@Url.Action("Index", "Manage")" class="btn btn-primary">Back</a>