eTimeTrack/Controllers/ExpensesController.cs
using Elmah.ContentSyndication;
using eTimeTrack.Helpers;
using eTimeTrack.Models;
using eTimeTrack.ViewModels;
using OfficeOpenXml.FormulaParsing.Excel.Functions.RefAndLookup;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eTimeTrack.Controllers
{
    [Authorize(Roles = UserHelpers.AuthTextUserAdministratorOrAboveExcludeTimesheetEditor)]
    public class ExpensesController : BaseController
    {
        [Authorize(Roles = UserHelpers.AuthTextUserPlusOrAbove)]
        public ActionResult ExpensesTypes()
        {
            int selectedProject = (int?)Session?["SelectedProject"] ?? 0;
            if (selectedProject == 0) { return InvokeHttp404(HttpContext); }
            var result = (from e in Db.ProjectExpenseTypes
                         join t in Db.ProjectTasks on e.TaskID equals t.TaskID
                         join v in Db.ProjectVariations on e.VariationID equals v.VariationID
                         where t.ProjectID == selectedProject
                         select new ExpensesTypes
                         {
                             ExpenseTypeID = e.ExpenseTypeID,
                             ExpenseType = e.ExpenseType,
                             TaskID = e.TaskID,
                             VariationID = e.VariationID,
                             Name = t.Name,
                             Description = v.Description,
                             ProjectId = t.ProjectID,
                             IsClosed = e.IsClosed,
                             IsCostRecovery = e.IsCostRecovery,
                             IsFeeRecovery = e.IsFeeRecovery
                         }).ToList();

            ViewBag.InfoMessage = TempData["InfoMessage"];
            return View(new ExpensesTypesViewModel
            {
                ExpensesTypesDetails = result
            }); 
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int? id)
        {
            ProjectExpenseType expensesTypes = Db.ProjectExpenseTypes.Where(x => x.ExpenseTypeID == id).FirstOrDefault();
            if(expensesTypes != null)
            {
                Db.ProjectExpenseTypes.Attach(expensesTypes);
                Db.ProjectExpenseTypes.Remove(expensesTypes);
                Db.SaveChanges();
            }
            TempData["InfoMessage"] = new InfoMessage(InfoMessageType.Success, "Succesfully deleted Expenses Types");
            return RedirectToAction("ExpensesTypes");
        }

        public ActionResult Create()
        {
            int selectedProject = (int?)Session?["SelectedProject"] ?? 0;
            ProjectExpenseType projectExpense = new ProjectExpenseType();
            projectExpense.ProjectID = selectedProject;

            SetViewbag(projectExpense.ProjectID);
            ViewBag.Source = Source.Create;
            return View("CreateEdit", projectExpense);
        }

        public ActionResult edit(int? id)
        {
            ProjectExpenseType projectExpense = Db.ProjectExpenseTypes.Find(id);
            SetViewbag(projectExpense.ProjectID);
            ViewBag.Source = Source.Existing;
            return View("CreateEdit", projectExpense);
        }

        [HttpPost]
        public ActionResult CreateEdit(ProjectExpenseType projectExpenseType, Source source)
        {
            ProjectExpenseType existing = Db.ProjectExpenseTypes.Find(projectExpenseType.ExpenseTypeID);
            projectExpenseType.LastModifiedBy = UserHelpers.GetCurrentUserId();
            projectExpenseType.LastModifiedDate = DateTime.UtcNow;
            if(existing != null)
            {
                Db.Entry(existing).CurrentValues.SetValues(projectExpenseType);
                Db.Entry(existing).State = EntityState.Modified;
            }
            else
            {
                Db.ProjectExpenseTypes.Add(projectExpenseType);
            }
            Db.SaveChanges();
            TempData["InfoMessage"] = new InfoMessage { MessageContent = $"Project Expense Type {projectExpenseType.ExpenseType}  Saved.", MessageType = InfoMessageType.Success };
            return RedirectToAction("ExpensesTypes");
        }

        private void SetViewbag(int? projectId)
        {
            ViewBag.ProjectID = new SelectList(Db.Projects, "ProjectID", "Name");
            ViewBag.TaskID = new SelectList(GetProjectTaskdetails(projectId), "TaskID", "DisplayName");
            ViewBag.VariationID = new SelectList(GetProjectVariationdetails(projectId), "VariationID", "DisplayName");
        }

        private List<ProjectTask> GetProjectTaskdetails(int? projectId)
        {
            var deta =  Db.ProjectTasks.Where(x => x.ProjectID == projectId && !x.IsClosed).OrderBy(x => x.Name).ToList();
            return deta;
        }
       
        private List<ProjectVariation> GetProjectVariationdetails(int? projectId)
        {
            return Db.ProjectVariations.Where(x => x.ProjectID == projectId && !x.IsClosed).OrderBy(x => x.Description).ToList();
        }
    }
}

eTimeTrack/Views/Expenses/CreateEdit.cshtml
@using eTimeTrack.Controllers
@using eTimeTrack.Helpers
@model eTimeTrack.Models.ProjectExpenseType

@{
    ViewBag.Title = ViewBag.Source + " Expense Type";
}

@Html.Partial("_Banner")
@Html.Partial("_InfoMessageRender")
@using (Html.BeginForm("CreateEdit", "Expenses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ExpenseTypeID)
    @Html.HiddenFor(model => model.ProjectID)
    @Html.Hidden("Source", (Source)ViewBag.Source)


    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">Project</label>
            <div class="col-md-10">
                <label class="labelFormValue" id="selectedProjectDisplay">@Session["SelectedProjectName"]</label>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseType, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpenseType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpenseType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Default Task</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TaskID, null, "Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TaskID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-2">Default Variation</label>
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.VariationID, null, "Select", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.VariationID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsClosed, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsClosed)
                    @Html.ValidationMessageFor(model => model.IsClosed, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsFeeRecovery, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsFeeRecovery)
                    @Html.ValidationMessageFor(model => model.IsFeeRecovery, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.IsCostRecovery, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsCostRecovery)
                    @Html.ValidationMessageFor(model => model.IsCostRecovery, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>


        <div class="pull-right">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>

    </div>
}

<a href='@Url.Action("ExpensesTypes", "Expenses")' class="btn btn-primary" role="button">Back</a>

eTimeTrack/Views/Expenses/ExpensesTypes.cshtml
@using eTimeTrack.Extensions
@using eTimeTrack.ViewModels
@model ExpensesTypesViewModel

@{
    ViewBag.Title = "Expenses Types";
}

@Html.Partial("_Banner")
@Html.Partial("_InfoMessageRender")

@using (Html.BeginForm("Create", "Expenses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="submit" id="submit"  class="btn btn-primary" value="Create New" />
}
<!-- Modal Delete Dialog -->
<div class="modal fade" id="confirmDeleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Confirm Delete</h4>
            </div>
            <div class="modal-body">
                Are you sure you want to delete this item?
            </div>
            <div class="modal-footer">
                @using (Html.BeginForm("DeleteConfirmed", "Expenses", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    <input type="hidden" id="deleteId" name="id" />
                    <input type="submit" class="btn btn-primary" id="btnDeleteConfirm" value="Delete">
                }
            </div>
        </div>
    </div>
</div>
<table class="table table-striped table-hover data-table" width="100%">
    <thead>
        <tr>
            <th>Expense Type</th>
            <th>Default Task</th>
            <th>Default Variation</th>
            <th data-orderable="false">IsClosed</th>
            <th data-orderable="false">IsFeeRecovery</th>
            <th data-orderable="false">IsCostRecovery</th>
            <th data-orderable="false">Edit</th>
            <th data-orderable="false">Delete</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.ExpensesTypesDetails.Count; i++)
        {
            <tr>
                <td>
                    @Model.ExpensesTypesDetails[i].ExpenseType
                </td>
                <td>
                    @Model.ExpensesTypesDetails[i].Name
                </td>
                <td>
                    @Model.ExpensesTypesDetails[i].Description
                </td>
                <td>
                    @Html.CheckBox("active", @Model.ExpensesTypesDetails[i].IsClosed, new { data_id = @Model.ExpensesTypesDetails[i].ExpenseTypeID, @class = "activeCheckbox" })
                </td>
                <td>
                    @Html.CheckBox("active", @Model.ExpensesTypesDetails[i].IsFeeRecovery, new { data_id = @Model.ExpensesTypesDetails[i].ExpenseTypeID, @class = "activeCheckbox" })
                </td>
                <td>
                    @Html.CheckBox("active", @Model.ExpensesTypesDetails[i].IsCostRecovery, new { data_id = @Model.ExpensesTypesDetails[i].ExpenseTypeID, @class = "activeCheckbox" })
                </td>
                <td>
                    <a href='@Url.Action("Edit", new {id = @Model.ExpensesTypesDetails[i].ExpenseTypeID})' class="btn btn-primary" role="button"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></a>
                </td>
                <td>
                    <button class="btn btn-primary delete" data-id="@Model.ExpensesTypesDetails[i].ExpenseTypeID" role="button"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></button>
                </td>
            </tr>
        }
    </tbody>
</table>

<a href="@Url.Action("Index", "Manage")" class="btn btn-primary">Back</a>

@section Scripts
{
    @Scripts.Render("~/bundles/notify")
    <script>
        $(document).ready(function () {
            $("body").on("click", ".delete", function () {
                $('#deleteId').val($(this).data('id'));
                $('#confirmDeleteModal').modal('show');
            });

        });
    </script>
}