eTimeTrack/ViewModels/ExpensesUploadViewModel.cs
using eTimeTrack.Extensions;
using System;
using System.ComponentModel.DataAnnotations;
using System.Web;
using System.Web.Mvc;

namespace eTimeTrack.ViewModels
{
    public class ExpensesUploadViewModel
    {
        [Key]
        public int ExpenseUploadID { get; set; }

        [Display(Name = "Project")]
        public int ProjectId { get; set; }

        [Display(Name = "Company")]
        public int CompanyId { get; set; }

        [Display(Name = "Invoice Number")]
        public string InvoiceNumber { get; set; }

        [Display(Name = "Transaction ID")]
        public string TransactionID { get; set; }

        [Required]
        [Display(Name = "Expense Item Date")]
        public string ExpenseDate { get; set; } 

        [Display(Name = "Costed In Week Ending")]
        public string CostedInWeekEnding { get; set; }

        [Required]
        public string Cost { get; set; }

        [Display(Name = "Home Office Type")]
        public string HomeOfficeType { get; set; }

        [Required]
        [Display(Name = "Employee Supplier Name")]
        public string EmployeeSupplierName { get; set; }

        [Display(Name = "Identifier")]
        public string UOM { get; set; }

        public string IdentifierValues { get; set; }

        [Display(Name = "Expenditure Comment")]
        public string ExpenditureComment { get; set; }

        [Display(Name = "Project Comment")]
        public string ProjectComment { get; set; }

        public int? AddedBy { get; set; }
        public DateTime? AddedDate { get; set; }

        [Required(ErrorMessage = "Please select file")]
        [FileExtension(Allow = ".xls,.xlsx", ErrorMessage = "Only excel file")]
        public HttpPostedFileBase file { get; set; }

        public SelectList ProjectList { get; set; }
        public SelectList CompanyList { get; set; }
    }
}

eTimeTrack/Controllers/ExpensesUploadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eTimeTrack.Helpers;
using eTimeTrack.Models;
using eTimeTrack.ViewModels;
using System.Data.Entity;
using System.IO;
using System.Web.Hosting;
using System.Threading.Tasks;
using Elmah.ContentSyndication;
using OfficeOpenXml;
using System.Globalization;
using OfficeOpenXml.FormulaParsing.Excel.Functions.DateTime;
using System.Text.RegularExpressions;
using static Spire.Pdf.General.Render.Decode.Jpeg2000.j2k.codestream.HeaderInfo;

namespace eTimeTrack.Controllers
{
    [Authorize(Roles = UserHelpers.AuthTextUserAdministratorOrAboveExcludeTimesheetEditor)]
    public class ExpensesUploadController : BaseController
    {
        [Authorize(Roles = UserHelpers.AuthTextUserPlusOrAbove)]
        public ActionResult Index()
        {
            ExpensesUploadViewModel viewModel = new ExpensesUploadViewModel
            {
                ProjectList = GenerateDropdownUserProjects(),
            };
            ViewBag.CompanyId = new SelectList(Getcompanydetails(), "Company_Id", "Company_Name");
            ViewBag.InfoMessage = TempData["Infomessage"];
            return View(viewModel);
        }

        [HttpPost]
        public JsonResult GetCompanyList(int? projectid)
        {
            if (projectid != null)
            {
                List<Company> company = (from c in Db.Companies
                                         join p in Db.ProjectCompanies on c.Company_Id equals p.CompanyId
                                         where p.ProjectId == projectid
                                         select c).OrderBy(x => x.Company_Name).ToList();

                return Json(company.Select(x => new
                {
                    CompanyId = x.Company_Id,
                    Name = x.Company_Name
                }));
            }
            return null;
        }

        [HttpPost]
        public ActionResult ImportExpensesTemplates(ExpensesUploadViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return InvokeHttp404(HttpContext);
                }
                model.ProjectList = GenerateDropdownUserProjects();
                var projectName = Db.Projects.Find(model.ProjectId).Name;
                ValidateExcelFileImportBasic(model.file);
                string targetFolder = Server.MapPath("~/Content/Upload");
                string targetPath = Path.Combine(targetFolder, model.file.FileName);
                model.file.SaveAs(targetPath);
                ProjectExpensesUpload projectExpensesUpload = new ProjectExpensesUpload()
                {
                    ProjectId = model.ProjectId,
                    CompanyId = model.CompanyId,
                    TransactionID = model.TransactionID,
                    ExpenseDate = model.ExpenseDate,
                    CostedInWeekEnding = model.CostedInWeekEnding,
                    Cost = model.Cost,
                    HomeOfficeType = model.HomeOfficeType,
                    EmployeeSupplierName = model.EmployeeSupplierName,
                    UOM = model.UOM,
                    ExpenditureComment = model.ExpenditureComment,
                    ProjectComment = model.ProjectComment,
                    InvoiceNumber = model.InvoiceNumber,
                    AddedBy = UserHelpers.GetCurrentUserId(),
                    AddedDate = DateTime.UtcNow
                };

                Db.ProjectExpensesUploads.Add(projectExpensesUpload);
                Db.SaveChanges();
                Employee user = UserHelpers.GetCurrentUser();
                HostingEnvironment.QueueBackgroundWorkItem(ct => ProcessXLSFile(model, user.Id, user.Email, projectName));
                TempData["InfoMessage"] = new InfoMessage { MessageContent = "The upload process will run in the background. You will receive an email notification when complete.", MessageType = InfoMessageType.Success };
                ViewBag.InfoMessage = TempData["Infomessage"];
            }
            catch (Exception ex)
            {
                TempData["InfoMessage"] = new InfoMessage
                {
                    MessageContent = "Error: could not import Expenses Upload data: " + ex.Message,
                    MessageType = InfoMessageType.Failure
                };
                ViewBag.InfoMessage = TempData["InfoMessage"];
            }
            return RedirectToAction("Index");
        }

        private async Task ProcessXLSFile(ExpensesUploadViewModel model, int userId, string email, string projectName)
        {
            int invalidRowsEmpty = 0;
            int insertedRows = 0;
            int rowsCount = 0;
            int duplicateRows = 0;
            List<List<int>> invalidRowsNoLinkRowNumbers = new List<List<int>>();
            ApplicationDbContext context = new ApplicationDbContext();
            try
            {
                #region Column Number methods
                int transactionID = ColumnNumber(model.TransactionID);
                int expenseItemDate = ColumnNumber(model.ExpenseDate);
                int costedInWeekEnding = ColumnNumber(model.CostedInWeekEnding);
                int cost = ColumnNumber(model.Cost);
                int homeOfficeType = ColumnNumber(model.HomeOfficeType);
                int employeeSupplierName = ColumnNumber(model.EmployeeSupplierName);
                int identifier = ColumnNumber(model.UOM);
                int expenditureComment = ColumnNumber(model.ExpenditureComment);
                int invoiceNumber = ColumnNumber(model.InvoiceNumber);
                #endregion

                byte[] fileData;
                using (MemoryStream target = new MemoryStream())
                {
                    model.file.InputStream.CopyTo(target);
                    fileData = target.ToArray();
                }
                List<ProjectExpensesUpload> expensesUpload = new List<ProjectExpensesUpload>();
                List<ProjectExpensesUpload> duplicateexpensesUpload = new List<ProjectExpensesUpload>();

                using (MemoryStream stream = new MemoryStream())
                {
                    stream.Write(fileData, 0, fileData.Length);
                    using (ExcelPackage package = new ExcelPackage(stream))
                    {
                        ExcelWorksheet ws = package.Workbook.Worksheets[1];
                        rowsCount = ws.Dimension.Rows - 1;
                        int colsCount = ws.Dimension.Columns;

                        for (int i = 2; i < int.MaxValue; i++) // skip header row
                        {
                            if (string.IsNullOrWhiteSpace(ws.Cells[i, 1].Text))
                            {
                                if (!string.IsNullOrWhiteSpace(ws.Cells[i + 1, 1].Text) || !string.IsNullOrWhiteSpace(ws.Cells[i + 2, 1].Text))
                                {
                                    continue;
                                }
                                break;
                            }
                            var transactionIDdetails = transactionID != 0 ? ws.Cells[i, transactionID].Text?.Trim() : null;
                            string exDate = expenseItemDate !=0 ? ws.Cells[i, expenseItemDate].Value?.ToString()?.Trim() : null;
                            var ischeckexdate = CheckDate(exDate);
                            DateTime expenDate = !ischeckexdate ? DateTime.FromOADate(Convert.ToDouble(exDate)) : Convert.ToDateTime(exDate);

                            string costDate = costedInWeekEnding != 0 ? ws.Cells[i, costedInWeekEnding].Value?.ToString()?.Trim() : null;
                            var ischeckcostdate = CheckDate(costDate);
                            DateTime cdate = !ischeckcostdate ? DateTime.FromOADate(Convert.ToDouble(costDate)) : Convert.ToDateTime(costDate);
                            var idevalues = string.Empty;
                            var idet = identifier != 0 ? ws.Cells[i, identifier].Value?.ToString()?.Trim() : null;
                            if (!string.IsNullOrEmpty(model.IdentifierValues) && !string.IsNullOrEmpty(idet))
                            {
                                if (model.IdentifierValues.Contains(";"))
                                {
                                    string[] values = model.IdentifierValues.Split(';');
                                    foreach (var v in values)
                                    {
                                        if (idet.ToLower().Equals(v.ToLower()))
                                        {
                                            idevalues += idet;
                                        }
                                    }
                                }
                                else
                                {
                                    if (model.IdentifierValues.ToLower().Equals(idet.ToLower()))
                                    {
                                        idevalues += idet;
                                    }
                                }
                            }
                            int stdtypeid = 0; int exptypeid = 0; bool existexpenses = false;
                            var homeoffics = homeOfficeType != 0 ? ws.Cells[i, homeOfficeType].Value?.ToString()?.Trim() : null;
                            if (!string.IsNullOrEmpty(homeoffics))
                            {
                                stdtypeid = context.ProjectExpensesStdDetails.Where(x => x.StdType.ToLower().Equals(homeoffics.ToLower())).Select(x => x.StdTypeID).FirstOrDefault();
                            }

                            if(stdtypeid != 0)
                            {

eTimeTrack/Views/ExpensesUpload/Index.cshtml
@using eTimeTrack.Helpers
@using eTimeTrack.Extensions
@using eTimeTrack.ViewModels
@model eTimeTrack.ViewModels.ExpensesUploadViewModel
@{
    ViewBag.Title = "Project Expenses Upload Template";
}

@Html.Partial("_Banner")
@Html.Partial("_InfoMessageRender")

@using (Html.BeginForm("ImportExpensesTemplates", "ExpensesUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div class="alert alert-info">
            <b>Note: </b>eTimeTrack will upload data from the first worksheet in the data source (XL) file and must include all inception to date data. Any previously uploaded data that is now not included in the import file for the company will be deleted. Please ensure there are no gap rows in the data as the process will stop at the first break in data.
        </div>
        <div class="form-group">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectId, new { @class = "control-label col-md-2 required" })
                @Html.DropDownListFor(model => model.ProjectId, Model.ProjectList, "Select", new { id = "ProjectSelector", @class = "form-control", required = true })
                @Html.ValidationMessageFor(m => m.ProjectId, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CompanyId, new { @class = "control-label col-md-2 required" })
                @Html.DropDownListFor(model => model.CompanyId, null, "Select", new { @class = "form-control", required = true })
                @*@Html.ValidationMessageFor(m => m.CompanyId, "", new { @class = "text-danger" })*@
            </div>
            <div class="form-group" style="padding-left:100px">
                <label class="control-label">
                    Select XLSX file
                </label>
                <input type="file" name="File" accept=".xlsx" required>
            </div>

            <div id="expensesupload-details-container" style="display: none; margin-bottom: 5rem;">
                <div class="form-group">
                    @Html.LabelFor(model => model.TransactionID, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TransactionID, new { htmlAttributes = new { @class = "form-control", style = "display: inline-block" } })
                        <span style="text-wrap: nowrap; color:red;">Warning: If Transaction Id is not available, please check that the import file does not contain any previously uploaded transactions</span>
                        @Html.ValidationMessageFor(m => m.TransactionID, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExpenseDate, new { @class = "control-label col-md-2 required" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ExpenseDate, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.ExpenseDate, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CostedInWeekEnding, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CostedInWeekEnding, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.CostedInWeekEnding, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cost, new { @class = "control-label col-md-2 required" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.Cost, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.HomeOfficeType, new { @class = "control-label col-md-2" })
                    <div class="col-md-10" style="margin-top: 15px">
                        @Html.EditorFor(model => model.HomeOfficeType, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.HomeOfficeType, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.InvoiceNumber, new { @class = "control-label col-md-2" })
                    <div class="col-md-10" style="margin-top: 15px">
                        @Html.EditorFor(model => model.InvoiceNumber, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.InvoiceNumber, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.EmployeeSupplierName, new { @class = "control-label col-md-2 required" })
                    <div class="col-md-10" style="margin-top: 15px">
                        @Html.EditorFor(model => model.EmployeeSupplierName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.EmployeeSupplierName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-2" style="text-align: right;">
                        <label class="control-label custom-label-with-info">
                            Identifier Column
                            <a class='tool-tip tool-tip-indent' data-toggle="tooltip" data-placement="right" title="Optional column - used to filter out rows that are not actual Expenses from the import.">
                                <i class='glyphicon glyphicon-info-sign'></i>
                            </a>
                        </label>
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.UOM, new { htmlAttributes = new { @class = "form-control", id = "type-identifier-column-input" } })
                        @Html.ValidationMessageFor(m => m.UOM, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group" id="identifier-text-group" style="@(string.IsNullOrWhiteSpace(Model.UOM) ? "display: none;" : null)">
                    <div class="col-md-2" style="text-align: right;">
                        <label class="control-label custom-label-with-info">
                            Identifier Values
                            <a class='tool-tip tool-tip-indent' data-toggle="tooltip" data-placement="right" title="This is a semi-colon separated list of identifier values that are used to determine which rows to include. For example, a text value entered of 'Normal hours;Overtime hours' will include all rows that have either 'Normal hours' or 'Overtime hours' in the Identifier column and exclude all else from importing. Note that the values require exact matches but will not be compared in a case sensitive manner.">
                                <i class='glyphicon glyphicon-info-sign'></i>
                            </a>
                        </label>
                    </div>
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IdentifierValues, new { htmlAttributes = new { @class = "form-control required" } })
                        @Html.ValidationMessageFor(m => m.IdentifierValues, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ExpenditureComment, new { @class = "control-label col-md-2" })
                    <div class="col-md-10" style="margin-top: 15px">
                        @Html.EditorFor(model => model.ExpenditureComment, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(m => m.ExpenditureComment, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>


        </div>
        <div class="pull-right">
            <input type="submit" value="Import" id="submit" class="btn btn-primary" />
        </div>
        <a href="@Url.Action("Index", "Manage")" class="btn btn-primary">Back</a>
    </div>
}


@section scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script>
        $(document).ready(function () {

            $('#ProjectSelector').change(function () {
                $.post('@Url.Action("GetCompanyList", "ExpensesUpload")', { projectid: $(this).val() }, function (data) {
                    $('#CompanyId').empty();
                    $('#CompanyId').append($('<option>').text('Select'));
                    for (var i = 0; i < data.length; i++) {
                        $('#CompanyId').append($('<option>', { value: data[i].CompanyId }).text(data[i].Name));
                    }
                    if (data.length === 1) {
                        $('#CompanyId').change();
                    }
                });
            });

            $('input[type=file]').change(function () {
                $('#expensesupload-details-container').show();

            });

            function showIdentifierText() {
                var identiferText = $('#identifier-text-group');
                identiferText.show();
            }

            function hideIdentifierText() {
                var identiferText = $('#identifier-text-group');
                identiferText.hide();
            }

            //$('#type-identifier-column-input').change(function () {
            $('#type-identifier-column-input').on('input', function () {

                var val = $(this).val();
                console.log('change', val);
                if (val) {
                    showIdentifierText();
                } else {
                    hideIdentifierText();
                }
            });

        });


    </script>


}